<template>
  <div class="animate-fade-in-up" :style="{ marginBottom: '36px' }">
    <!-- Assistant header -->
    <div
      class="flex items-center gap-2.5 flex-wrap"
      :style="{ marginBottom: '14px', fontSize: '12px', color: 'var(--fg-3)', fontWeight: 500 }"
    >
      <span
        class="font-display flex items-center justify-center flex-shrink-0"
        :style="{
          width: '24px', height: '24px', borderRadius: '6px',
          background: 'var(--brand)', color: 'white',
          fontSize: '10px', fontWeight: 800, letterSpacing: '-0.02em',
        }"
      >F</span>
      <span>
        Floo
        <template v-if="message.modeLabel">
          · used <strong :style="{ color: 'var(--fg-2)', fontWeight: 600 }">{{ message.modeLabel }}</strong> mode with the project rules
        </template>
      </span>

      <!-- Provider · model badge. Surfaces "GLM · glm-4.5" on real replies
           and a dashed "Mock" pill when the server fell back (no API key) so
           the difference between a real GLM answer and the canned response
           is visible at a glance. -->
      <span
        v-if="isMockProvider"
        :title="'No AI provider configured on the server — this is a deterministic mock response.'"
        :style="{
          padding: '2px 6px',
          borderRadius: 'var(--r-xs)',
          background: 'var(--bg-2)',
          color: 'var(--fg-3)',
          fontSize: '10.5px',
          fontWeight: 600,
          letterSpacing: '0.02em',
          border: '1px dashed var(--border)',
        }"
      >Mock — configure an AI provider</span>
      <span
        v-else-if="message.model || message.provider"
        class="inline-flex items-center"
        :title="`This response was generated by ${providerLabel}${message.model ? ' (' + message.model + ')' : ''}`"
        :style="{
          gap: '4px',
          padding: '2px 6px',
          borderRadius: 'var(--r-xs)',
          background: 'var(--bg-2)',
          color: 'var(--fg-3)',
          fontSize: '10.5px',
          fontWeight: 600,
          letterSpacing: '0.02em',
          border: '1px solid var(--border-soft)',
        }"
      >
        <Icon name="lucide:cpu" class="w-3 h-3" />
        <span>{{ providerLabel }}<template v-if="message.model"> · {{ message.model }}</template></span>
      </span>
    </div>

    <!-- Prelude (editorial italic) -->
    <p
      v-if="message.content"
      :style="{
        fontFamily: 'var(--font-editorial)',
        fontSize: '14.5px',
        color: 'var(--fg-2)',
        lineHeight: 1.65,
        marginBottom: '16px',
        maxWidth: '720px',
        whiteSpace: 'pre-wrap',
      }"
    >{{ message.content }}</p>

    <!-- Output cards -->
    <ChatOutputCard
      v-for="card in message.outputCards"
      :key="card.id"
      :card="card"
      :message-id="message.id"
    />

    <!-- Web-search citations (research/competitor/trend modes) -->
    <div
      v-if="message.citations?.length"
      :style="{
        marginTop: '8px',
        padding: '10px 14px',
        background: 'var(--surface-2)',
        border: '1px solid var(--border-soft)',
        borderRadius: 'var(--r-md)',
      }"
    >
      <div
        class="inline-flex items-center"
        :style="{
          gap: '5px',
          padding: '3px 8px',
          marginBottom: '8px',
          borderRadius: 'var(--r-xs)',
          background: 'var(--brand-tint)',
          color: 'var(--brand)',
          fontSize: '11px',
          fontWeight: 600,
          border: '1px solid color-mix(in srgb, var(--brand) 18%, transparent)',
        }"
      >
        <Icon name="lucide:globe" class="w-3 h-3" />
        Grounded with web search · {{ message.citations.length }}
        {{ message.citations.length === 1 ? 'source' : 'sources' }}
      </div>
      <ul :style="{ margin: 0, padding: 0, listStyle: 'none', fontSize: '12px', lineHeight: 1.5 }">
        <li
          v-for="(c, i) in message.citations"
          :key="i"
          :style="{ marginBottom: '4px' }"
        >
          <a
            v-if="c.url"
            :href="c.url"
            target="_blank"
            rel="noopener"
            :style="{ color: 'var(--brand)', textDecoration: 'none' }"
          >{{ c.title || c.url }}</a>
          <span v-else :style="{ color: 'var(--fg-2)' }">{{ c.title }}</span>
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ChatMessage } from '~/types/chat'

const props = defineProps<{
  message: ChatMessage
}>()

/**
 * The persisted assistant row carries `metadata.provider` and `metadata.model`.
 * Show the mock pill whenever EITHER explicitly says "mock" — older rows that
 * pre-date the provider field will only have `model === 'mock'`, and the
 * mock fallback in `server/utils/ai.ts` always sets both.
 */
const isMockProvider = computed(
  () => props.message.provider === 'mock' || props.message.model === 'mock',
)

/** Human-readable provider name. Falls back to the raw id if unknown. */
const providerLabel = computed(() => {
  switch (props.message.provider) {
    case 'glm':       return 'GLM'
    case 'openai':    return 'OpenAI'
    case 'anthropic': return 'Anthropic'
    case undefined:   return 'AI'   // pre-provider rows
    default:          return props.message.provider
  }
})
</script>
