-- ============================================================
-- Seed Phase 1 of the rich skill library: 7 marketing skills + 1 creator skill.
-- Each row carries a full Anthropic-grade SKILL.md body in `instructions`
-- and 2-4 worked examples in `examples`. workspace_id = NULL means visible
-- to every workspace as a system skill.
--
-- Source of truth: floo-content/skills-source/*.md (one file per skill).
-- This migration is generated by build_seed_migration.py — do not hand-edit.
-- Re-run the generator and re-create the migration to update content.
-- ============================================================

INSERT INTO public.skills
  (name, category, description, instructions, examples, is_custom, workspace_id)
VALUES
  ('Brand Review', 'marketing', 'Audit a draft against brand voice and style guide. Flag issues by severity with before/after fixes.',
   $instr$
## Purpose

Audit a piece of content against the project's configured brand voice, DO/DON'T rules, and hashtag policy — and against general legal/clarity hygiene — surfacing every deviation as a flag the user can act on. This is a *judgement* skill: Floo should be specific and confident, not exhaustive and noisy.

## When to use

- The user pastes a draft (caption, hook, thread, script, blog post) and asks for a check, audit, or review.
- The user is about to ship and wants a final sanity pass.
- The user is comparing two or more candidate drafts and wants to know which is closest to brand.

Do **not** trigger this skill when the user asks for a *new* draft from scratch — that's `mk-draft-content`.

## Inputs to gather

1. **The draft itself.** Required. If missing, ask one question: "Paste the draft here, or point me to the file." Don't fabricate one.
2. **The target channel.** Optional — if the project's platform isn't the channel for this draft, the user must say so (e.g. project is TikTok but they're auditing a LinkedIn post).
3. **Severity tolerance.** Optional. Default to flagging High/Medium/Low. If the user says "just the deal-breakers", suppress Low.

The brand voice, DO/DON'T rules, hashtags, and platform profile are already in the system prompt — read them as canonical. Saved exemplars are the strongest possible signal: if the draft visibly diverges from saved exemplars in length, vocabulary, or structure, that's a finding.

## Evaluation dimensions

Run the draft against each dimension. Skip dimensions that don't apply (e.g. SEO doesn't apply to Stories).

### 1. Voice and tone
- Does the draft match the brand voice attributes? Cite the specific phrase that drifts.
- Are there register shifts within the draft (e.g. casual line then corporate line)?
- If the brand voice is bilingual (Bahasa + English code-switching), check both halves carry their weight — neither feels translated or tacked-on.

### 2. DO / DON'T rule compliance
- For each DO rule: does the draft honour it? If not, name the rule and the violating phrase.
- For each DON'T rule: does the draft contain a forbidden word, structure, or tone? Treat any DON'T violation as automatically High severity.

### 3. Stopping power (first line)
- Does line 1 earn the scroll-stop? Vague openers ("In today's world…", "Let's talk about…", "Have you ever wondered…") are flags.
- Platform-specific: TikTok/Reels need a verbal or visual hook in the first 1.5 seconds; LinkedIn carries 1-2 lines before the "see more" cut.

### 4. Length and rhythm
- Match the brand's documented sentence-length cadence.
- Match the platform conventions (TikTok captions <150 char land best; LinkedIn 1-3 short paragraphs; X is 280).
- Flag run-on sentences in brands that ship short sentences, and vice versa.

### 5. Hashtag and CTA hygiene
- Hashtags: are they on the project's approved list? Are they on-brand for the channel (3-5 on Instagram, 1-2 on LinkedIn, none on X usually)?
- CTA: is there exactly one ask, and is it a specific verb ("save", "comment your pick", "tap link")? "Engage with us" is not a CTA.

### 6. Legal / compliance flags
Always check, even when the brand voice is configured:
- Unsubstantiated superlatives ("the best", "#1", "guaranteed") without evidence.
- Health, financial, or earnings claims that need disclaimers.
- Comparative claims naming a competitor (legal exposure).
- Quoted testimonials without attribution.
- Trademarked terms without proper symbol or capitalization.

## Output format

Render exactly this structure:

### Summary
One paragraph (2-3 sentences). Lead with overall ship-readiness ("Ship as-is" / "One revision away" / "Significant rewrite needed"). Then the single biggest strength and the single biggest issue.

### Findings
A markdown table with columns: **Issue · Location · Severity · Suggestion**. Severity is High / Medium / Low. Sort by severity descending. If there are zero findings, write "No issues — ready to ship." and skip the rest of the sections.

### Revisions (top 3)
For the three highest-severity issues, show before/after as a Markdown blockquote:
> Before: …
> After: …

Keep "After" tight — same character count or shorter, never longer. The fix should be implementable, not theoretical.

### Compliance flags
Only render if any were found. List as bullets with the specific phrase + the recommended action ("add disclaimer", "qualify or remove", "verify before publishing").

## After delivering

Close with exactly one short prompt offering the obvious next step:
- If the draft is High-severity laden: "Want me to rewrite the full draft?"
- If only Low-severity: "Ready to publish — want me to draft the next post in the series?"
- If two drafts were compared: "Want me to merge the strongest moments from each into one final draft?"

Never offer more than two follow-ups. Never offer "Would you like me to also do X, Y, or Z?" laundry lists.

## Anti-patterns to avoid

- ❌ Generic feedback ("could be more engaging"). Always cite the specific phrase.
- ❌ Adding findings to look thorough. If the draft is clean, say so in one line.
- ❌ Recommending changes that violate a documented DON'T rule, even if "industry best practice".
- ❌ Suggesting a fix that's longer than the original on a brand whose voice is short-form.
- ❌ Ignoring the project's saved exemplars when the draft visibly contradicts them.
$instr$,
   ARRAY[$ex0$User pastes a caption draft → Floo returns Summary (1 line) + Findings table (Issue / Location / Severity / Suggestion) + revised top-3 high-severity lines + a follow-up prompt offering to revise the full draft.$ex0$, $ex1$User pastes 3 candidate captions → Floo audits each separately under its own H3 heading, applies the same severity scale, and ranks them at the end by ship-readiness.$ex1$, $ex2$User says 'review this against our voice' with no draft attached → Floo asks ONE clarifying question (paste the draft or share the file path) instead of guessing.$ex2$]::text[],
   false, NULL),
  ('Campaign Plan', 'marketing', 'Build a full campaign brief — objective, audience, channel mix, content calendar, success metrics.',
   $instr$
## Purpose

Translate a marketing goal into an executable campaign plan: a single-page brief with an objective, a positioning line, audience segments, channel allocation, a week-by-week content calendar, and measurable KPIs. The output should be specific enough that a team could start producing assets the next day.

## When to use

- The user is launching a product, running a lead-gen push, building awareness, or driving an offer.
- The user has a goal but no plan, or a vague plan and wants structure.
- The user has been writing one-off posts and wants a campaign frame to organize them.

Do **not** trigger this skill for a single-post brief — that's `mk-draft-content`. Do not trigger it for analysis of an already-shipped campaign — that's `mk-performance-report`.

## Inputs to gather

Ask in one round, not piecemeal:

1. **Goal.** Required. Phrase the outcome, not the activity. "Drive 500 trial signups" is a goal; "post on TikTok" is not. If the user gives an activity, push back: "What's the underlying outcome?"
2. **Timeline.** Required. Start date and duration (typically 2-8 weeks).
3. **Audience.** Required if not in the project context. Role, life stage, motivation. Dig past demographics to behaviours.
4. **Channels.** Default to the project's platform plus 1-2 logical neighbours. Confirm before assuming.
5. **Budget posture.** Optional. "No paid", "modest", "significant" — bucketing is enough; don't ask for line items.
6. **Existing assets.** Optional. Saved exemplars and brand-knowledge files give the strongest signal — read them before designing the calendar.

If 3+ are missing, ask once with all the gaps in a single message. Don't ping-pong.

## Frameworks

### Goal → primary KPI mapping

| Goal | Primary KPI | Secondary KPI |
|------|-------------|---------------|
| Awareness | Unique reach | Brand search lift |
| Engagement | Saves + shares | Comment quality (long replies > emojis) |
| Lead gen | Form submits or DMs | Cost per lead |
| Sales / conversions | Conversions | ROAS |
| Community | Repeat engagement, follows from existing audience | DM volume |
| Loyalty / retention | Re-purchase rate | Owned-channel CTR (email, push) |

Pick exactly one primary KPI. Vague goals ("more engagement") collapse into a measurable one before drafting the plan.

### Pillar logic
Build the content calendar around 3 (max 4) pillars. Each pillar serves the goal differently — Hook (top of funnel), Proof (mid), Push (bottom). On a 4-week plan, pillar mix typically: Week 1 Hook-heavy, Week 2 Hook + Proof, Week 3 Proof + Push, Week 4 Push + retargeting/recap.

### Channel allocation
- **Primary channel** = where the audience already pays attention. Allocate ~60% of effort here.
- **Secondary channel(s)** = where they convert or re-engage. ~30%.
- **Owned channel** (newsletter, DMs, broadcast list) = ~10%, but disproportionately important for retargeting.
- Drop a channel if the brand voice doesn't survive the platform's conventions — better to skip than dilute.

### Budget posture rules
- **No paid:** plan 1.5-2× the post volume; lean on collabs and UGC reposts; expect slower compounding reach.
- **Modest:** boost top-2 organic posts per week + retarget engagers in the final week.
- **Significant:** dedicated paid social tracks (cold + retarget); plan creative variants per audience segment.

## Output format

Render in this exact order. No deviation.

### Objective
One sentence. Goal + measurable target + timeframe. "Drive 500 free-trial signups across IG + TikTok in 4 weeks."

### Positioning line
One sentence the team can say out loud. The single message every piece of content should reinforce. Brand-voice native — not a generic value prop.

### Audience
2-4 segments. For each: a one-line behavioural sketch ("designers in their late 20s who follow accounts like X and Y, save more than they post"), and the pillar(s) most relevant to them.

### Channel mix
A table: **Channel · Role · Volume · Note**. Note column captures the format bias ("vertical video, hook in 1.5s") or platform constraint ("hashtags off-brand for X — use 0").

### Content calendar
A table: **Week (or Day) · Pillar · Format · Platform · CTA · Owner**. Owner column is "Floo" if the asset can be produced in this app, "Team" if it needs human capture (UGC, on-set photo). Cap at one row per asset; aggregate batches.

### KPIs
Primary KPI with a target number. 1-2 secondary KPIs with directional targets (↑ or specific %). Be honest about confidence — if the user has no historical baseline, write "directional only — establish baseline in week 1".

### Risks
3-5 bullets. Specific, not generic. "TikTok algo doesn't surface 5+ posts/week from accounts under 1k — pace 3/week max" beats "audience growth is hard".

### Quick wins
Top 3 things the user could ship in the first 48 hours to start the campaign with momentum.

## After delivering

Close with one of these (pick the most useful):
- "Want me to draft the week-1 hook posts?"
- "Want me to build the email sequence that supports this?" (defer to `mk-email-sequence`)
- "Want me to flag what existing assets we have that could be repurposed for week 1?"

## Anti-patterns to avoid

- ❌ Generic frameworks ("AIDA", "AARRR") name-dropped without applying them. If you cite a framework, render the table with the actual content slotted in.
- ❌ Calendars padded with placeholder rows ("TBD content"). Every row is concrete or it doesn't ship.
- ❌ Vanity KPIs (impressions, reach) when the goal is conversions.
- ❌ Recommending channels the brand voice can't carry. Brand alignment > channel reach.
- ❌ Ignoring the project's existing saved exemplars when picking formats — if the brand has shipped 6 carousels and 0 reels, don't build a reel-heavy plan without acknowledging the shift.
$instr$,
   ARRAY[$ex0$User: 'Plan a 4-week campaign for our new ceramic line, IG + TikTok, modest budget.' → Floo returns Objective + One-line positioning + Audience (3 segments) + Channel mix table + 4-week calendar table (week × pillar × format × platform) + KPIs with targets + Risks + 2-line follow-up.$ex0$, $ex1$User asks for a 1-week launch sprint instead → Floo collapses the calendar to a daily table (Day · Pillar · Format · Platform · CTA) and skips the weekly grouping.$ex1$, $ex2$User says 'we have no budget' → Floo drops the paid row from the channel mix table, increases the volume of organic posts, and flags the realistic reach trade-off in Risks.$ex2$]::text[],
   false, NULL),
  ('Competitive Brief', 'marketing', 'Compare positioning vs named competitors. Surface content gaps, threats, and opportunity angles.',
   $instr$
## Purpose

Compare the project's brand against named competitors on positioning, content patterns, voice, and execution — then surface the gaps the brand can credibly claim and the threats it should defend against. Output is a decision-grade brief, not an essay.

## When to use

- The user names 1-5 competitors and wants a comparison.
- The user is building a sales battlecard.
- A competitor just made a move (launch, pivot, viral post) and the user wants a response read.
- The user is stuck on positioning and wants to find white space.

Do **not** trigger this skill for analyzing the user's own past performance — that's `mk-performance-report`. Don't trigger it for general market research with no named competitors — that's `research` mode.

## Inputs to gather

1. **Competitors.** Required. At least one named account/brand. If user gives a category ("other coffee shops") push for 2-3 specific names.
2. **Comparison surface.** Required. "Their IG", "their landing page", "their last 3 launches", "their voice". Default to the project's primary platform if unspecified.
3. **Use case.** Required, default to "positioning brief". Other options: sales battlecard, threat response, white-space hunt.
4. **Recent context.** Optional but useful — paste recent posts, paste their landing page, attach screenshots. Do not invent specifics about competitors you can't see.

## Frameworks

### Positioning grid
Pick 2 axes the user's category competes on. Common axes: **price ↔ premium**, **mass ↔ niche**, **functional ↔ emotional**, **playful ↔ serious**, **fast ↔ deliberate**. Place each named brand on the grid with one defensible sentence per placement. The brand's white space = the empty quadrant nobody owns.

### "Owns / Tries / Avoids" frame
For each competitor, fill three buckets:
- **Owns:** the territory they've earned — formats, words, rituals their audience associates with them. ("@brandA owns the daily-routine carousel.")
- **Tries:** territory they reach for but don't dominate — content they post but doesn't perform. ("@brandA tries founder-voice reels but the engagement drops 40%.")
- **Avoids:** what they pointedly don't do, deliberately or by accident. ("@brandA avoids any price talk.")

The user's brand's opportunity sits in either: (a) something competitors avoid that the user can credibly do, or (b) something competitors try and fail at that the user can do better.

### Content gap grid
A table: **Topic · Who covers it · How well · Gap?**. "Gap?" is yes/no — yes means there's room to claim it. Floo's job is to find topics where the answer is yes AND the brand voice can credibly carry it.

### Threat triage
For competitor moves, classify:
- **Existential** — they've claimed something fundamental to your positioning. Respond fast.
- **Adjacent** — they've moved into your space but their voice/audience doesn't carry it. Watch, don't respond.
- **Distraction** — they're doing something showy in territory neither of you should be in. Ignore.

### Voice diff
Side-by-side voice attributes table. Brand voice is configured in the project context — read it. For each competitor, infer 3-5 voice attributes from their copy (cite a phrase as evidence). The diff is where the user can sharpen — not by becoming opposite, but by being more *deliberately themselves*.

## Output format

Render in this order. Skip sections that don't apply to the use case (battlecard skips the IG-specific gap section; threat response leads with Threat triage).

### TL;DR
Two sentences. Where the user's brand sits relative to the competitive set, and the single most actionable move.

### Positioning grid
A 2-axis ASCII or table representation. List each brand's coordinate and the one-sentence reasoning.

### Owns / Tries / Avoids
One block per competitor. Three short bullets each.

### Content gaps
3-5 specific gaps. For each: the gap topic + why competitors don't own it + a one-line angle the user could lead with.

### Threats
0-3 threats. Each labelled Existential / Adjacent / Distraction with a one-line response posture.

### Opportunities
3 specific angles the user could claim in the next 30 days. Each angle paired with a candidate hook line written in the brand voice.

### Voice differentiation
A short table or 3 bullets — what the user should *do more of* and *do less of* to be unmistakably themselves vs. the set.

## After delivering

Pick the single highest-leverage follow-up:
- "Want me to draft the week-1 posts that claim the [named gap]?"
- "Want me to turn this into a sales battlecard format?"
- "Want me to write the response post for the [named threat]?"

## Anti-patterns to avoid

- ❌ Inventing competitor specifics ("@brandA has 200k followers" — don't fabricate). If you don't see it, say "based on what you described" or ask.
- ❌ SWOT-style abstractions ("their strength is consistency"). Always cite an observable artifact — a hook, a thumbnail, a posting cadence.
- ❌ Recommending the user copy a competitor verbatim. Translate insights into brand-voice-aligned moves.
- ❌ Generic "differentiate by being more X" advice. Differentiation lives in specific words, formats, and rituals — not adjectives.
- ❌ Building gaps the brand voice can't credibly carry. White space the brand can't enter is not white space.
$instr$,
   ARRAY[$ex0$User: 'Compare us to @brandA and @brandB on IG.' → Floo returns Positioning grid (table) + What they own / What we own + 3 content gaps + 2 threats + 3 opportunity angles + 1 follow-up to draft posts that claim a named gap.$ex0$, $ex1$User asks for a battlecard for sales → Floo reframes the same analysis as a one-pager with Pitch / Counter-pitch / Proof points / Objection handling, suppressing the IG-specific bits.$ex1$, $ex2$User: 'A competitor just launched a feature like ours' → Floo runs the analysis through a threat lens: how big is the move, what's the response window, what's the brand-voice-aligned counter.$ex2$]::text[],
   false, NULL),
  ('Draft Content', 'marketing', 'Generate channel-specific drafts with SEO and headline variants, sized to the platform.',
   $instr$
## Purpose

Generate marketing content drafts — captions, hooks, threads, blog posts, landing copy, press releases, case studies — sized correctly for the channel, in the project's brand voice, with the right structural signals (headlines, hooks, CTAs, SEO).

## When to use

- The user asks to write, draft, generate, or compose any marketing content.
- The user wants variations (3 hooks, 5 captions, 3 subject lines).
- The user wants to translate one piece of content into another channel.

Do **not** trigger this skill when the user asks for an audit of an existing draft (that's `mk-brand-review`) or a multi-step email flow (that's `mk-email-sequence`).

## Inputs to gather

Default to producing the work, ask only when blocking:

1. **Content type + channel.** Required. Caption, hook, thread, blog, email, landing, press release, case study. If channel is ambiguous, default to the project's platform.
2. **Topic.** Required. If the user's prompt has a clear topic, run with it.
3. **Length / count.** Required for variations ("how many?"). For long-form, infer from the type (blog ~600-1200 words; case study ~400-800).
4. **Key message.** Optional but high-leverage. If the user gives one, anchor every variant to it.
5. **Constraints.** Optional. Hashtag policy, character ceiling, mandatory CTA, links.

If the user gives 3 of these in their prompt, just produce. Don't ask. Asking when you could have produced is the most common failure mode of this skill.

## Channel playbook

### Instagram caption
- 1 hook line (≤125 char visible before the more-cut).
- 2-4 short paragraphs OR a 1-line punchy caption — match the brand's documented cadence.
- Hashtags **at the end**, separated by 2 line breaks. 3-7 tags from the approved list.
- One CTA verb. "Save this for [specific use]" beats "double-tap if you agree".

### TikTok / Reels caption
- ≤150 char total. Lead with the topical hook — don't repeat what's already on screen.
- Trending phrases only if the brand voice allows.
- Hashtags inline at the end. 3-5 max.
- Hook line is for the algorithm and the comments — not the viewer (they're watching the video).

### Twitter / X
- Single tweet: ≤280 char. One idea. No hashtags unless on-brand. Punchline last.
- Thread: tweet 1 is the hook, tweets 2-N are one beat each, final tweet is the payoff + CTA. Number them ("1/", "2/").

### LinkedIn post
- Hook in line 1 (the "see more" cut hits ~210 char on most viewports).
- 2-4 short paragraphs, each one idea. Whitespace between every paragraph.
- Specific numbers, named people, real examples. Generic advice is invisible on LinkedIn.
- Hashtag block at the end, 3-5 tags.

### Threads
- Treat like X but with longer-form latitude (500 char). Conversational, less "thought leadership" register.

### Email newsletter
- Subject line variants (3). Different angles: curiosity / specific / direct.
- Preheader (≤80 char) that completes or contradicts the subject — never repeats it.
- Body: hook → one promise → payload → one CTA button text.
- Sign-off in the brand voice.

### Blog post (long-form)
- 3 headline candidates. Mix angles: how-to / contrarian / list.
- TL;DR (2-3 sentences).
- H2/H3 outline structure, one beat per section.
- Lead paragraph that earns the first scroll.
- Internal/external linking suggestions (don't fabricate URLs — note where a link belongs).
- Meta description (≤155 char) and primary keyword.

### Landing page
- Headline + subheadline (3 variants of the headline).
- Hero benefit (one sentence, value-first).
- 3-4 feature/benefit blocks (heading + 1-2 lines each, lead with the user outcome).
- Social proof slot (label what to put there: testimonial, logo strip, stat).
- Primary CTA + secondary CTA. Different verbs.
- FAQ stub: 3-5 questions worth answering on-page.

### Press release
- Headline (AP-style title case, no marketing fluff).
- Dateline + lead paragraph (who, what, when, where, why).
- Quote slot from a named exec — write a placeholder if the user hasn't supplied one and flag it.
- Boilerplate slot.
- Media contact slot.

### Case study
- Result-forward title ("How [Customer] cut [metric] by [X]").
- Customer overview block (industry, size, prior state).
- Challenge → Solution → Result structure with specific numbers in Result.
- Customer-quote slot (flag if missing).
- CTA at the end pointing to the next step (demo, contact, related case study).

## Output format

Always:
1. The draft itself — clean, no commentary inside variants.
2. A single short trailer line: which brand-voice cues you applied (e.g. "Used short-sentence cadence and avoided exclamation marks per brand DON'T list.").
3. SEO/structure notes (only when relevant to the channel — blog, landing, press release).
4. One follow-up question — see "After delivering".

Variations are returned as a numbered list with **no commentary between items**. Each item is shippable copy. No "here's another option" preambles.

## After delivering

Pick the single most useful follow-up:
- "Want me to translate this for [adjacent channel]?"
- "Want me to A/B variants of the top 2?"
- "Want me to write the visual brief / image direction to pair with this?"
- "Want me to audit it against the brand voice before you ship?" (defers to `mk-brand-review`)

## Anti-patterns to avoid

- ❌ Filler phrases the brand voice doesn't use ("In today's world…", "Let's talk about…", "Have you ever wondered…").
- ❌ Variants that are paraphrases of each other. Genuine variation = different angle, structure, or hook type.
- ❌ Hashtags inside the caption body when the brand convention is end-blocked.
- ❌ Adding emojis when the brand voice forbids them.
- ❌ Inventing specifics (real customer names, specific numbers, fake URLs). When you need a placeholder, label it explicitly: "[insert metric here]".
- ❌ Producing 8 variants when the user asked for 3.
- ❌ Writing in English when the brand's voice + saved exemplars are Indonesian (or vice versa). Match the language register the brand actually ships.
$instr$,
   ARRAY[$ex0$User: 'Draft 5 IG hook lines for Friday's reel about clay sourcing.' → Floo returns a numbered list of 5 standalone hook lines (no preamble), then a single short line confirming which brand-voice cues were applied.$ex0$, $ex1$User: 'Write the LinkedIn version of this caption' (paste IG caption) → Floo translates voice and length to LinkedIn (2-3 short paragraphs, see-more break in line 1, professional CTA), preserves the core message, and lists what was changed at the end.$ex1$, $ex2$User: 'Blog post about our Bali workshop, 800 words' → Floo returns 3 headline candidates + a TL;DR + the post structured H2/H3 with one section per beat + meta description (≤155 chars) + suggested primary keyword + a closing line offering to cut a 60-second reel script from the same beats.$ex2$]::text[],
   false, NULL),
  ('Email Sequence', 'marketing', 'Design multi-email flows with copy, timing, branching logic, and exit conditions.',
   $instr$
## Purpose

Design a multi-email flow end-to-end: who it's for, what triggers it, what each email does, when it sends, what makes a recipient exit, and how the flow's success is measured. Output is implementable in any ESP (Klaviyo, HubSpot, Mailchimp, etc.) — the user copies the copy, sets the delays, and ships.

## When to use

- Onboarding / welcome series.
- Lead nurture (post-download, post-demo).
- Re-engagement / win-back.
- Product launch announcements (T-minus 14 / 7 / 3 / launch / day-after).
- Upsell or expansion sequences for existing customers.

Do **not** trigger this skill for:
- A single one-off email — use `mk-draft-content`.
- A campaign that spans multiple channels (email is one of many) — use `mk-campaign-plan`, then loop back here for the email leg.

## Inputs to gather

1. **Sequence type.** Required. Welcome, nurture, re-engage, win-back, launch, upsell.
2. **Trigger.** Required. What event puts a recipient in this flow? (Signup, lead form fill, 30 days no purchase, etc.)
3. **Goal.** Required. The action you want the recipient to take. Be specific — "open emails" is not a goal; "book a demo" is.
4. **Length.** Optional, default by type: welcome 3-5; nurture 5-7; re-engage 3; win-back 3; launch 4-5; upsell 2-3.
5. **Audience signal.** Optional but high-leverage — what they did to get here, what they already know, what they expect.

If the user gives a goal + trigger, draft the sequence; don't interview further.

## Frameworks

### Sequence shapes by type

- **Welcome:** Email 1 (immediate, "you're in") → 2 (Day 2, "here's how to get value fast") → 3 (Day 4, story / proof) → 4 (Day 7, soft ask) → 5 (Day 10, hard ask). Exit on goal action.
- **Lead nurture:** Email 1 (deliver the lead magnet, set expectation) → 2-4 (build relevance and trust through specific use cases or stories) → final (call to action, low-friction conversion). Exit on conversion or unsubscribe-soft (move to broadcast list).
- **Re-engage:** 3 emails over 14 days. Email 1: "hey, are you still in?" — light, no ask. Email 2: best content from the period they missed. Email 3: "last note" — explicit "we'll stop emailing if you don't engage". Exit on click; auto-suppress if no engagement after email 3.
- **Win-back:** 3 emails. Email 1: curiosity hook ("we noticed…"). Email 2: reason to come back (specific, not generic — new product, lower price, different format). Email 3: final offer or graceful goodbye. Exit on purchase.
- **Launch:** T-14 (tease), T-7 (preview to list), T-3 (early-access for top engagers), Launch Day (full announce), T+1 (social proof / FOMO). Branch: top engagers get T-3, others skip to launch day.
- **Upsell:** 2-3 emails. First: "you've used X — here's the next level." Second: "here's how a customer like you used it." Third (optional): "limited window" with deadline.

### Timing logic
- Welcome: front-load. Email 1 within 5 minutes of trigger.
- Nurture: 2-4 day gaps; never two emails on consecutive days.
- Win-back: longer gaps (5-7 days) — they've already disengaged; pressure makes it worse.
- Launch: tightening gaps as the day approaches.
- Time-of-day: respect audience timezone. Default to 9-11 AM local for B2B, 6-8 PM local for consumer.

### Exit and branching rules
Every sequence needs explicit exit conditions per email:
- Goal-action exit: click the primary CTA, complete the action, etc.
- Suppression exit: hard bounce, unsubscribe.
- Branch exits: opened email 1 + clicked → skip to advanced track; ignored 3 in a row → suppress.

Document these in plain language inside each email block — never leave them implicit.

### A/B testing rule of thumb
Only A/B-test what you'll act on. Default suggestions: subject line on email 1 (highest leverage), CTA copy on the conversion email, send time on the re-engagement opener. Don't recommend testing send-day-of-week unless you have ≥5,000 recipients per variant.

## Output format

### Goal
One sentence: the action + the segment + the timeframe.

### Audience
One paragraph. Who they are, what they did to enter this sequence, what they know.

### Flow diagram
A simple Mermaid diagram or ASCII flowchart showing the sequence, branches, and exit points. Keep it small — this is for orientation, not architecture.

### Sequence
For each email, render this exact block:

```
Email N — Day [delay] · Send time [time]
Subject: [primary subject]
Subject (alt 1): [variation]
Subject (alt 2): [variation]
Preheader: [≤80 char]

Body:
[draft copy in the brand voice — full text, not a summary]

CTA: [primary button text]
Secondary CTA: [link if applicable, else "none"]

Exit condition: [what removes the recipient from the rest of the flow]
Branch condition: [if applicable — what moves them to a different track]
```

### KPIs
- Primary metric (open rate target or click rate target — pick one based on the goal).
- Conversion target on the goal action.
- Unsubscribe ceiling (typically <0.3% per email; flag if exceeded).

### A/B test suggestions
2-3 specific tests, each with hypothesis + variant + sample size guidance.

## After delivering

- "Want me to write the landing-page copy that catches the click from email N?"
- "Want me to draft the social posts that drive traffic into this sequence?"
- "Want me to design the re-engagement track for recipients who exit without converting?"

## Anti-patterns to avoid

- ❌ Sequences with no exit conditions. A flow without an exit is a spam machine.
- ❌ "Email 4: follow up." Stub copy is not a draft. Write the email or don't include it.
- ❌ Aggressive cadence (daily emails on a nurture flow). It tanks deliverability.
- ❌ Generic subject lines ("Hi", "Quick question", "{firstName}"). The user can write those without us.
- ❌ Identical CTAs on every email. Vary by intent stage.
- ❌ A/B-testing tiny audiences. If the user's list is <2k, recommend skipping tests and shipping the better-bet single version.
$instr$,
   ARRAY[$ex0$User: 'Build a 5-email welcome sequence for new newsletter subscribers' → Floo returns Goal + Audience + Sequence flow diagram (Mermaid or ASCII) + per-email block (Send, Subject + 2 alts, Preheader, Body, CTA, Exit condition) + KPI targets + 2 A/B suggestions + follow-up to draft any single email in full.$ex0$, $ex1$User: 'Win-back for customers who haven't bought in 90 days' → Floo defaults to a 3-email sequence (curiosity → reason → final), branches to drop the third email if they engage with email 1 or 2, and writes the exit condition explicitly per email.$ex1$, $ex2$User: 'Just write me a single welcome email' → Floo declines this skill scope and hands back to mk-draft-content with the user's original prompt.$ex2$]::text[],
   false, NULL),
  ('Performance Report', 'marketing', 'Translate raw metrics into an exec-ready report with wins, misses, and prioritized next actions.',
   $instr$
## Purpose

Turn raw performance data into an executive-readable report that says what worked, what didn't, *why*, and what to do next. The output should be a brief a marketing lead would forward to their CMO without rewriting it.

## When to use

- The user wants to wrap a campaign or a period (week / month / quarter).
- The user pastes raw metrics, exports from Meta / TikTok / GA, or names a date range.
- The user asks "how did we do?", "what's working?", or "what should we change?".

Do **not** trigger this skill to design a *future* campaign — that's `mk-campaign-plan`. Don't trigger it for a one-post post-mortem (just answer in chat).

## Inputs to gather

1. **Period.** Required. Date range or campaign name. Always specify the comparison period (prior period, prior year, baseline) — you can't say "growth" without a baseline.
2. **Source data.** Required. Pasted CSV, screenshots, or a summary the user dictates. Do not invent numbers. If the user gives no numbers and no comparison, ask once.
3. **Audience for the report.** Default to "marketing lead". Other options: founder, exec / CMO, the user themselves (private analysis).
4. **Goal context.** Optional but high-leverage — what was the campaign trying to do? Without a goal, "good" and "bad" are subjective.

## Frameworks

### What goes in a "headline number"
Pick the single number that matters most given the goal. Format: number + delta + context. "1,247 trial signups, +38% vs prior month, on flat budget." Do not lead with a vanity metric (impressions) when a downstream metric (conversions) tells the truer story.

### Wins are causal, not just positive
A win isn't "engagement up 12%" — it's "engagement up 12%, driven by the carousel format we shipped 3× this month, vs 1× last month". Always pair the metric with the *thing the team did* that probably caused it. If you can't identify the cause, label it "unattributed" and flag it as something to investigate.

### Misses are honest, not defensive
A miss isn't "TikTok was disappointing" — it's "TikTok views fell 30%, likely because we shipped 1 post/week vs the 3/week needed for algo lift." Be specific about cause. "Algorithm changes" is a non-answer unless you have evidence.

### Next actions are ranked, not listed
Three actions, ranked by impact-to-effort. For each:
- The action.
- The metric it should move.
- The size of the bet (small / medium / large).
- The signal that tells you to keep going (or stop).

### "What did we learn?" filter
Every report ends with at least one learning the team can carry into the next cycle. A finding that doesn't change behaviour is a finding nobody needs.

## Output format

### Headline
One sentence + the headline number. State the period and the goal.

### Top numbers
A 5-row table: **Metric · This period · Prior period · Delta · Note**. Sort by goal-relevance, not alphabetical. Bold the headline number's row.

### Wins
3 wins. For each: the metric movement + the post / campaign / experiment that drove it + a one-line lesson. If you can't attribute it, write "unattributed — worth investigating".

### Misses
2 misses. For each: what fell short + the most-likely cause + the corrective action.

### Patterns
1-2 paragraphs covering second-order observations: what content type performed, what time-of-day, what audience segment over- or under-indexed. Specific examples > generalizations.

### Next actions
A ranked list of 3. For each:
- **Action** — one sentence, verb-led.
- **Metric to move** — the specific number you're trying to improve.
- **Size of bet** — small / medium / large.
- **Signal to keep going** — what success looks like at the 2-week or 4-week check-in.

### Asks (for executive audience only)
Resources, budget, or decisions the user needs. Skip this section unless audience = exec/CMO.

## After delivering

- "Want me to plan the next cycle based on these learnings?" (defers to `mk-campaign-plan`)
- "Want me to draft the team Slack summary of this report?"
- "Want me to dig into [specific metric] more?"

## Anti-patterns to avoid

- ❌ Reporting metrics without comparison ("we got 50k views"). Without a baseline, a number is meaningless.
- ❌ Inventing causes. If you don't know why something moved, say so. "Unattributed" is honest; making up a story is a confidence-undermining habit.
- ❌ Listing 12 next actions. Three ranked actions ship; twelve unranked ones don't.
- ❌ Vanity-metric leading. Reach is fine on an awareness goal but irrelevant on a conversion goal.
- ❌ Generic learnings ("post more on TikTok"). Specific learnings ("the founder-voice cuts outperformed product cuts 3:1, lean into founder format next month") drive different behaviour.
- ❌ Defensive language about misses. "Underperformed due to market conditions" is the corporate equivalent of "the dog ate my homework". Be specific or admit uncertainty.
$instr$,
   ARRAY[$ex0$User pastes a CSV of last 30 days IG performance → Floo returns Headline (1 line) + Top numbers (5 metrics with delta vs prior period) + Wins (3 with the post that earned it) + Misses (2 with the candid reason) + Next actions (3, ranked) + 1 follow-up offering to plan the next cycle.$ex0$, $ex1$User: 'Last week's stats vs the week before' → Floo collapses the report to a 1-page weekly format: Top numbers + 1 win + 1 miss + 2 next actions + a comment on which patterns from last week to repeat or kill.$ex1$, $ex2$User: 'My boss needs a Q2 recap' → Floo expands to executive format: Headline / What worked (with the campaign that earned it) / What didn't (with the lesson) / Looking ahead (priorities for Q3) / Asks (resources or decisions needed).$ex2$]::text[],
   false, NULL),
  ('SEO Audit', 'marketing', 'Keyword research, on-page checks, content gaps, technical issues, prioritized action plan.',
   $instr$
## Purpose

Run an SEO audit on a site, a section, or a single page — surfacing the issues, opportunities, and prioritized fixes. Floo doesn't have crawler access; the user is the crawler. The skill's job is to turn what the user can paste or describe into a usable plan.

## When to use

- The user wants an SEO health check on their site or blog.
- The user wants help picking a primary keyword for a new page.
- The user has a page that's underperforming and wants a diagnosis.
- The user wants to find content gaps competitors are ranking for.

Do **not** trigger this skill for general "improve our marketing" — too vague. Push the user to name what they want audited.

## Inputs to gather

1. **Surface.** Required. Specific URLs, a section ("our blog"), or a single page.
2. **Visible source data.** Strongly preferred — paste page titles, meta descriptions, H1s, body copy snippets. Without these, Floo guesses; with them, Floo audits.
3. **Goal.** Optional. Rank for specific terms / drive product page traffic / build topical authority. Without a goal, you can't prioritize.
4. **Known constraints.** Optional. CMS limitations, domain authority context, geographic targeting, language(s).

If the user pastes nothing, ask for at least the URLs and the page titles before proceeding. Don't fabricate page contents.

## Frameworks

### Audit dimensions (per page)

For each page in scope, evaluate:

| Dimension | What to check |
|-----------|---------------|
| **Title tag** | Length 50-60 char. Primary keyword early. Brand name at end (if at all). |
| **Meta description** | Length 140-160 char. Includes primary keyword. Sells the click — doesn't just describe. |
| **H1** | One H1 per page. Matches search intent. Echoes (not repeats) the title. |
| **URL** | Short, lowercase, hyphen-separated, keyword-bearing. Not auto-generated IDs. |
| **Heading hierarchy** | H2/H3 tree is logical. Each H2 is a sub-topic; H3s are facets within. |
| **Word count** | Match the SERP norm for the query intent (transactional ~600-1200; informational deep-dive ~1500+). |
| **Internal linking** | At least 2 inbound from related pages; at least 3 outbound to related content. |
| **Image SEO** | Filenames are descriptive (not `IMG_5829.jpg`). Alt text present and meaningful. |
| **Schema markup** | Article, Product, FAQ, Breadcrumb where applicable. |
| **Page speed flags** | Visible: too many images above the fold, video autoplay, embedded ads. |

### Search intent classification
Every keyword has an intent. Floo's job is to make sure the page matches the intent.

| Intent | Signal in the query | Page type that wins |
|--------|---------------------|---------------------|
| Informational | "what is", "how to", "best way to" | Blog post, guide, tutorial |
| Navigational | A brand or product name | Brand homepage, product page |
| Commercial | "best X", "X vs Y", "X review" | Comparison post, review, listicle |
| Transactional | "buy X", "X price", "X near me" | Product page, pricing page, local landing page |

A common SEO failure: an informational query landed on a transactional page (or vice versa). Always check fit.

### Keyword difficulty banding
Without a tool, infer difficulty from SERP signals the user can describe:
- **Easy:** SERP is dominated by forum threads, low-DA blogs, no big brands. Niche or long-tail.
- **Medium:** SERP has 2-3 strong brand results but also some smaller sites. Achievable for a well-optimized page.
- **Hard:** SERP is mostly enterprise sites, news outlets, or Wikipedia. Requires significant authority + content depth.

If the user has paid tools (Ahrefs / SEMrush / Moz), invite them to share difficulty scores. Otherwise band qualitatively and label it "estimated".

### Quick wins vs. strategic bets
Every audit splits findings two ways:
- **Quick wins:** ≤1 hour each, high impact. Title tag rewrites, meta descriptions, internal links, alt text fixes.
- **Strategic bets:** weeks of work, compounding impact. Topical clusters, content rewrites, link-building campaigns, site architecture changes.

Most users need quick wins first — show momentum, build the case for strategic bets.

## Output format

### Headline
One sentence: top-level health, biggest opportunity.

### Quick wins (≤1 hour each)
Ranked list of 5. Per item: **Page · Issue · Fix · Expected impact (qualitative)**. Sort by impact-to-effort.

### Strategic bets (weeks of work)
3 bets. Per item: **Bet · Why · Effort estimate (S/M/L) · Success metric**.

### Per-URL findings
A table: **URL · Title · Meta · H1 · Word count · Internal links · Notes**. Mark each cell with ✅ pass / ⚠️ issue / ❌ fail. The Notes column carries the one-line diagnosis when something is off.

### Keyword opportunities
A table: **Keyword · Intent · Difficulty band · Existing page (if any) · Recommended action**. Recommended action is one of: optimize existing page / create new page / merge into [other page] / skip (wrong intent).

### Technical flags
Bullet list of anything technical the user mentioned or is visible from URL structure: HTTPS, canonical tags, redirect chains, mobile-friendliness, Core Web Vitals signals.

### Content gaps
3 specific gaps competitors are ranking for that the user could credibly claim. For each: the topic + a candidate title + the primary keyword + the recommended page type.

## After delivering

- "Want me to draft the rewrite for [highest-impact URL]?" (defers to `mk-draft-content`)
- "Want me to map this into a quarterly content calendar?" (defers to `mk-campaign-plan`)
- "Want me to dig into the [specific page] in more depth?"

## Anti-patterns to avoid

- ❌ Inventing keyword volumes or difficulty scores. Floo doesn't have a keyword tool — qualitative bands only, labelled as estimates.
- ❌ Fabricating page contents you didn't see. If the user didn't paste it, ask or skip the page.
- ❌ "Add more keywords" advice. Modern SEO is about intent fit and depth, not keyword density.
- ❌ Recommending fixes that require things the user can't do (server-side schema injection on a hosted-blog platform, etc.). Match the recommendation to the user's likely access level.
- ❌ Long lists of generic findings. Five ranked quick wins beats twenty unranked ones.
- ❌ Treating "rank #1" as the goal regardless of intent. Sometimes the user's page shouldn't try to win a query — it should try to win a *different* one.
$instr$,
   ARRAY[$ex0$User: 'Audit our blog for SEO' (pastes 5 URLs) → Floo returns Headline + Quick wins (5, ranked) + Strategic bets (3) + Per-URL findings table (URL · Title issue · Meta issue · H1 issue · Internal links · Content gap) + Keyword opportunities (10 with intent + difficulty band) + 1 follow-up to draft the rewrite for the top URL.$ex0$, $ex1$User: 'Help us pick a primary keyword for the new product page' → Floo runs a focused keyword cluster instead of full audit: 8-12 candidates with intent (Informational / Commercial / Transactional), seasonality, and one-line on why each could or couldn't carry the page.$ex1$, $ex2$User: 'Why isn't our top blog post ranking?' → Floo runs a single-URL diagnostic: Title/Meta/H1/word count/internal-link review + intent-fit check + competitor SERP guess + 3 specific edits ranked by likely impact.$ex2$]::text[],
   false, NULL),
  ('Skill Creator', 'creator', 'Guide the user through scoping, drafting, and validating a new custom skill.',
   $instr$
## Purpose

Help the user author a high-quality custom skill from scratch — or improve an existing one. A good skill is a small, decidable, well-scoped instruction module the AI can apply consistently across many requests. The Skill Creator's job is to keep skills focused, specific, and testable.

## When to use

- The user wants to create a new skill from scratch.
- The user has a draft skill and wants it reviewed or improved.
- The user is stuck on what to put in `instructions` or `examples`.
- The user keeps re-typing the same instructions across chats and wants to systematize.

Do **not** trigger this skill for editing project-level rules (those live in `Project context → Rules`) or brand voice (that's a different system entirely).

## What makes a good skill

A skill is good when these are all true:

1. **Single purpose.** The skill does one thing. "Audit a draft" is one thing. "Audit a draft and also rewrite it and also publish it" is three things — split them.
2. **Trigger clarity.** A user (or the AI) should be able to tell *at a glance* whether this skill applies. The When-to-use section is decidable, not vibes-based.
3. **Decidable instructions.** Every framework or rule in the body should produce the same answer regardless of which AI session reads it. "Be conversational" is not decidable; "Use contractions, address the reader as 'you', avoid passive voice" is.
4. **Concrete examples.** Two to four short examples show the *shape* of a correct response. Examples are the highest-leverage part — when in doubt, the model imitates the examples over the prose.
5. **Anti-patterns named.** What the skill must *not* do is often more important than what it should do. Negative examples prevent regression.

## The discovery loop

When the user wants to author a new skill, run this loop. Don't skip steps; don't combine them.

### Step 1: Trigger
Ask: "What does the user say or do that should activate this skill?"

The answer is a list of phrases or situations. If the user can't name them, the skill isn't well-scoped yet — push back: "Give me three real moments from the last week where you wanted this."

### Step 2: Output shape
Ask: "When this skill works perfectly, what does the response look like? Sketch the structure — sections, length, format."

If the user says "good content", that's not a shape. Push: "Show me the headings. Tell me the length. Tell me the structure."

### Step 3: Anti-patterns
Ask: "What's the failure mode? When this skill goes wrong, what does the bad response look like?"

This is the question that surfaces hidden taste. Most users find it easier to describe "wrong" than "right".

After all three answers, draft the skill body using the structure below.

## Skill body template

Every skill renders to this structure (matches Anthropic's SKILL.md convention adapted for Floo):

```markdown
## Purpose
One paragraph: what the skill does, and what makes it different from adjacent skills. If this skill could be confused with another in the library, name the difference.

## When to use
Bullet list of trigger conditions. Use action verbs ("user asks for…"). Include a short list of "do not trigger when…" cases too.

## Inputs to gather
Numbered list of what the AI needs from the user before producing output. Mark required vs optional. Note which inputs the project context already provides.

## Frameworks / decision rules
The substantive content — the dimensions to evaluate, the structure to follow, the rules of thumb. Use tables for spectrums and lookups. This is where the skill earns its keep.

## Output format
Exact structure of the response: section headings, table columns, length guidance. Be prescriptive. Specificity here is what makes the skill apply consistently.

## After delivering
A closing prompt suggesting the next step. Pick the single most useful follow-up — not a laundry list.

## Anti-patterns to avoid
Negative examples. The behaviours this skill must NOT exhibit. As specific as the positive instructions above.
```

## Validation rubric

Once the draft is ready, walk through this checklist with the user:

- [ ] A reader can tell from the first paragraph what this skill does and when to use it.
- [ ] The When-to-use section has at least one "do not trigger when…" entry.
- [ ] At least one input is required; required inputs have a "what to do if missing" rule.
- [ ] At least one framework or table is concrete (numbers, named structures, decidable rules).
- [ ] The Output format section is detailed enough that two different AI runs would produce structurally similar output.
- [ ] At least one anti-pattern is named.
- [ ] At least 2 examples are written, each ≤2 sentences.
- [ ] The whole skill could be tested on a real example in under 5 minutes.

If 2+ items fail, revise before saving. A weak skill in the library is worse than no skill — it'll trigger and produce mediocre output.

## Output format

### Skill name + slug
Title Case name. Lowercase-hyphen slug.

### Category
One of: voice / format / trend / workflow / marketing / creator. If unsure, propose two and let the user pick.

### Description (one line)
The card subtitle. ≤90 characters. Reads like a verb phrase: "Generate X, given Y, in the style of Z."

### Instructions body
Full markdown, structured per the template above. Don't truncate — this is what the AI will read at inference time.

### Examples (2-4)
Each example is one sentence describing a representative input → response shape. Examples power imitation more than the prose does — invest in them.

### Validation report
Run the rubric. List which items pass and which fail. Suggest fixes for the fails.

### Test prompt
Suggest one specific user message that should trigger this skill and produce a clean response. The user should test it before saving.

## After delivering

- "Want me to walk through the validation checks one more time and tighten weak spots?"
- "Want me to draft a second skill that pairs with this one?"
- "Want me to write a test prompt and predict the response so you can compare?"

## Anti-patterns to avoid

- ❌ Skills that do many things. Split or skip.
- ❌ Vibes-based instructions ("be on-brand", "match the voice") with no operational rule. Either define the rule or trust the brand-voice system to handle it.
- ❌ Examples that are paraphrases of each other. Each example should test a different facet of the skill.
- ❌ Skills that duplicate something already in the library. Search before authoring; merge rather than fork.
- ❌ Drafting a skill before knowing the trigger and the failure mode. Discovery loop first, draft second.
- ❌ Skills written entirely in prose with no decidable rules or tables. The body should look like a checklist, not an essay.
$instr$,
   ARRAY[$ex0$User: 'Help me make a skill for our weekly recap post format' → Floo runs the discovery loop (3 questions: trigger, output shape, anti-pattern), drafts a Skill.md (Purpose / When to use / Inputs / Frameworks / Output / After delivering / Anti-patterns), and asks the user to test it on one real example before saving.$ex0$, $ex1$User pastes their existing rough custom-skill draft → Floo reviews it against the rubric (specificity / decidability / examples / anti-patterns) and returns a tightened version with diff explanations.$ex1$, $ex2$User: 'I need a skill that does everything for IG' → Floo pushes back: skills must do one thing well. It proposes 3 narrower skill candidates and asks which to author first.$ex2$]::text[],
   false, NULL);
